spring:
  application:
    name: DataCenter

app:
  version: 0.1.1

dataSource:
  type: FOLDER
  path: C:/Rock/Datas/Calypso/Persistence/dataCenter1

logging:
  config: classpath:fintech/logback.xml

configs:
  taskConfigFolder: task

persistent:
  type: FILE
  folder: /calypso/Calypso

event:
  generate: true
  folder: event/#yyyyMM#

local:
  file:
    root: C:/Rock/Datas/Calypso/Persistence/dataCenter