#Rock Local Service, connect to ROCK_DEV env
server:
  port: ${SERVER_PORT:10001}

persistent:
  type: FOLDER
  srcPath: C:/Rock/Datas/DataCenter/apps/Calypso/FireFight_129

local:
  file:
    root: C:/Rock/Datas/DataCenter/apps/Calypso/FireFight_129