spring:
  application:
    name: DataCenter

app:
  version: 0.1.1

dataSource:
  type: FOLDER
  path: C:/Rock/Datas/DataCenter/apps/Calypso/FireFight_129

logging:
  config: classpath:fintech/logback.xml
  controller:
    exception:
      printStack: true

configs:
  taskConfigFolder: task

persistent:
  type: FILE
  folder: /calypso/Calypso

event:
  generate: true
  folder: event/#yyyyMM#

local:
  file:
    root: C:/Rock/Datas/DataCenter/apps/Calypso/FireFight_129